### ISSUE TITLE
process as many calibrators as needed

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/a2p2#15]
In ASPRO, one can link more than one calibrator to a star. When at least a pair object+calibrator is defined, a2p2 opens a folder on P2 with the name of th escience object. The folder contains the PB for the science object and the calibrator.
A2P2 should create in this folder all the calibrator's OBS, not the 1st one.

**Comment by gmella** [comment]
Right! This has been implemented thanks to user's feedback. in v0.3.8:

- Enhance CAL SCI sequence : [CAL1] SCI [CAL2 [SCI CAL3 [...] ] ]
