### ISSUE TITLE
password is visible

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/a2p2#21]
the password for account is visible, and since it takes 1 full minute to connect to P2, this is a bit annoying...

**Comment by gmella** [comment]
**** are now present in the password field during the GUI login since version 0.2.3
Is there  another place where you can read this password ?
Which version are you using ?
current pip version is 0.2.5

**Comment by GillesDuvert** [comment]
OK, I had 0.2.2. Closed.
