### ISSUE TITLE
Not finding the right container id?

### ISSUE THREAD

**Issue by kluskaj** [JMMC-OpenDev/a2p2#22]
Hi all,

I am trying to use a2p2 to put MATISSE OBs into p2 but I get the following error message:
In P2 my container ID is 2658970 whereas a2p2 looks for 105051700.

Could you please check it? (or did I do something wrong?)
Thanks!

Jacques

> General error or Absent Parameter in template!
>  Missing magnitude or OB not set ?
> 
> Error :
>  Traceback (most recent call last):
>   File "/anaconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 95, in processOB
>     instrument.submitOB(ob, self.containerInfo)
> p2api.p2api.P2Error: (404, 'POST', 'https://www.eso.org/cop/api/v1/containers/105051700/items', "No container with id '105051700'.")
>  
>  Please check LOG and fix before new submission.

> Traceback (most recent call last):
>   File "/anaconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 95, in processOB
>     instrument.submitOB(ob, self.containerInfo)
>   File "/anaconda3/lib/python3.6/site-packages/a2p2/vlti/instrument.py", line 54, in submitOB
>     folder, _ = api.createConcatenation(p2container.containerId, folderName)
>   File "/anaconda3/lib/python3.6/site-packages/p2api/p2api.py", line 320, in createConcatenation
>     return self.createItem('Concatenation', containerId, name)
>   File "/anaconda3/lib/python3.6/site-packages/p2api/p2api.py", line 260, in createItem
>     return self.post('/containers/%d/items' % containerId, {'itemType': itemType, 'name': name})
>   File "/anaconda3/lib/python3.6/site-packages/p2api/p2api.py", line 1466, in post
>     return self.request('POST', url, data, etag)
>   File "/anaconda3/lib/python3.6/site-packages/p2api/p2api.py", line 1409, in request
>     raise P2Error(r.status_code, method, url, r.json()['error'])
> p2api.p2api.P2Error: (404, 'POST', 'https://www.eso.org/cop/api/v1/containers/105051700/items', "No container with id '105051700'.")

**Comment by gmella** [comment]
Hi Jaaack,

  I just sent this issue to ESO colleagues. The current workarround is to create a folder using P2 webinterface and restart again with a2p2.
For info, we just released this morning a2p2  V 0.2.8 that helps to create OBs on P104 and P105.
`pip install -U a2p2` may help ;)

Thank you for your feedback!
Guillaume

**Comment by gmella** [comment]
The workarround is no more required if you use the fresh  a2p2-0.2.9 release.
Please close this issue if that is fine on your side.
