### ISSUE TITLE
TypeError: 'NoneType' object is not iterable 

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/a2p2#24]
aspro2 21.10 beta 7  + a2p2 v.0.3.7 :
sendind an object (gravity or matisse or pionier all the same), gives:
```
Traceback (most recent call last):
  File "/home/gildas/.local/lib/python3.7/site-packages/a2p2/vlti/facility.py", line 104, in processOB
    instrument.checkOB(ob)
  File "/home/gildas/.local/lib/python3.7/site-packages/a2p2/vlti/gravity.py", line 89, in checkOB
    self.checkIssVltiType(acqTSF)
  File "/home/gildas/.local/lib/python3.7/site-packages/a2p2/vlti/instrument.py", line 137, in checkIssVltiType
    vltitypePref=[v for v in self.facility.a2p2client.preferences.getConfigKeys(psection) if self.isInRange(acqTSF.tpl, "ISS.VLTITYPE", v) ]
TypeError: 'NoneType' object is not iterable
```
comes from line 137 in instrument.py where vltitypePref is not correctly initialized, setting
` vltitypePref=['snapshot']`
instead at this line saves the day.

IMHO this comes from vltitypePref not present in the xml sent by Aspro, but  21.10 beta 7 is the last availble Aspro distro.
Probably cannot harm if vltitypePref was set to ['snapshot'] when it is not present in the Aspro SAMP message.

**Comment by gmella** [comment]
Ok, this was a bug in preferences and it has been fixed. 
However we had some discussions and propose to start with a simple workarround. VLTIType will be filled with all supported modes from [ "snapshot", "imaging", "time-series", "astrometry"]. The OB will be accepted without warning on this side. The user will latter uncheck non relevant modes in P2 web interface.
