### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by agallenne** [JMMC-OpenDev/a2p2#25]
This very useful tool has never worked for me. I just tried again but I can't log in the ESO portal. It stays stuck with:

`
INFO - a2p2.gui  - 2022-07-12 13:20:46,165 - gui.py:180 - Sorry, your PIONIER OB can't be submitted, please log in first, select container and send OB again from Aspro2.'

'INFO - a2p2.vlti.facility  - 2022-07-12 13:21:07,264 - facility.py:170 - Connecting to p2 api...'

'INFO - a2p2.gui  - 2022-07-12 13:21:08,635 - gui.py:180 - Connected to p2 api (production)`

I am on MacOs 12.2 and Python 3.8.13

**Comment by gmella** [comment]
Sorry for the late reply. Other mac users run properly the tool and we will pinpoint your issue.
Please, may you try to launch a2p2 with -v option. If you upgrade a2p2, you may get the last release that fills the OB tree much faster. 
Please send us the detailed report if you still get stucked.

**Comment by gmella** [comment]
We checked with Alexandre all together and new a2p2 version figures out to display his long RUN list.
