### ISSUE TITLE
Improve and correct the action when submitted OB does not match the instrument template

### ISSUE THREAD

**Issue by jean-philippeberger** [JMMC-OpenDev/a2p2#26]
# Description

Currently, when one OB is submitted through aspro2 to Aspro with a parameter that does not match the instrument template requirement the user gets the following pop-up error message (example)

> Value error :
> K mag (2.310000) is out of ranges [2.500000,11.000000]
> for this mode (tel=AT, spec=LOW, pol=OUT, dualFeed=False) 
> Aborting submission to P2. Please check LOG and fix before new submission.

This leads of all the OB submission process to be aborted by a2p2.

# Desirable evolution

## Improve the message

In order for the user to understand the message it should be modified as follows

**Add** 
"WARNING: According to the template manual (Number P109b (provide most recent version))"
K mag (2.310000) is out of ranges [2.500000,11.000000]  (replace ranges by range)
**Add** for target xxx (provide the target name corresponding to the incorrect OB)

## Enable submission anyways

Such errors should not prevent the user to submit their OBs to P2. It is their responsibility to correct it.
So the a2p2 process should not be aborted and the  "OK" button could be replaced by a simple "Proceed" button that will allow the submission.

**Comment by gmella** [comment]
"OK" button can't be renamed using simple tk widgets. 
Extracted dit table has been updated and version is also added as metadata to build the warning message.
The smallest or biggest accepted DIT is used given to the K value so the process can continue. 
A new release is coming...

**Comment by jean-philippeberger** [comment]
Thanks.

Then the simplest thing would be to add the following text

"Click "OK" to proceed  "NO" to abort the submission  and the corresponding NO button that will abort the submissino process.

**Comment by gmella** [comment]
Done in last version 0.5.2 
A single window as to proceed or abort if batch contains one or more warning. This could be extended to errors so the user can proceed if he does not want to correct it in Aspro2....
