### ISSUE TITLE
Removing the * in the name of stars from Simbad

### ISSUE THREAD

**Issue by mmontarges** [JMMC-OpenDev/a2p2#31]
When obtained from Simbad or SearchCal, some star names start with the * character. P2 rejects this.

I added `obTarget.name = obTarget.name.replace('*', '')` after lines 69-70 in vlti/pionier.py

I suppose the same line should be added for GRAVITY and MATISSE. I tested for PIONIER only, it works.

Cheers.

Miguel

**Comment by gmella** [comment]
Thank you @mmontarges for your feedback, we will apply a patch for every instrument following ESO rules : https://www.eso.org/sci/observing/phase2/p2intro/p2-tutorials/p2-ImportTargetList.html
